DROP TABLE PERSONA IF EXIST;
CREATE TABLE PERSONA(
    ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
    DNI VARCHAR(20),
    FIRST_NAME VARCHAR(50),
    SECOND_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    SECOND_LAST_NAME VARCHAR(50)
);